export interface TimelineEvent {
  year: number;
  dateLabel: string;
  content: string;  // full segment text, never truncated
}

export interface TimelineResult {
  events: TimelineEvent[];
  hasTimeline: boolean;
  confidence: number;
}

interface Marker {
  index: number;
  endIndex: number;
  dateStr: string;
  year: number;
}

// ── Helpers ────────────────────────────────────────────────────────────

function parseYearFromDateStr(dateStr: string): number | null {
  const m4 = dateStr.match(/(\d{4})/);
  if (m4) return parseInt(m4[1], 10);

  const century = dateStr.match(/(\d{1,2})\s*世[纪紀]\s*(\d{1,2})\s*年[代]/);
  if (century) return (parseInt(century[1], 10) - 1) * 100 + parseInt(century[2], 10);

  return null;
}

/** Convert any date expression into a numeric-only label. */
function normalizeDateLabel(raw: string, year: number): string {
  // Already numeric with range: "1978 年至 1995 年" → "1978-1995"
  const rangeM = raw.match(/(\d{4})\s*年?\s*(?:至|到|—|-|～|~)\s*(\d{4})\s*年?/);
  if (rangeM) return `${rangeM[1]}-${rangeM[2]}`;

  // Simple "1992年" → "1992"
  const simpleM = raw.match(/^(\d{4})\s*年?/);
  if (simpleM) return simpleM[1];

  // "(-1983年）" → "1983"
  const parenM = raw.match(/[（(]\s*(?:-)?(\d{4})\s*年?\s*[）)]/);
  if (parenM) return parenM[1];

  // "20 世纪 90 年代" → "1990"
  const centM = raw.match(/(\d{1,2})\s*世[纪紀]\s*(\d{1,2})\s*年[代]/);
  if (centM) return String(year);

  // English: "in 1992" → "1992"
  const engM = raw.match(/(?:in|around|about|circa|since|by|before|after|during|from)\s+(\d{4})/i);
  if (engM) {
    const prefix = raw.match(/^(in|around|about|circa|since|by|before|after|during|from)/i);
    if (prefix && prefix[1].toLowerCase() === 'before') return `< ${engM[1]}`;
    if (prefix && prefix[1].toLowerCase() === 'after') return `> ${engM[1]}`;
    return engM[1];
  }

  // "the 1980s" → "1980s"
  const decadeM = raw.match(/the\s+(\d{4})s/i);
  if (decadeM) return `${decadeM[1]}s`;

  // "between 1978 and 1995" → "1978-1995"
  const engRangeM = raw.match(/(?:between|from)\s+(\d{4})\s+(?:and|to|until)\s+(\d{4})/i);
  if (engRangeM) return `${engRangeM[1]}-${engRangeM[2]}`;

  // Standalone year
  const soloM = raw.match(/(\d{4})/);
  if (soloM) return soloM[1];

  return raw;
}

function buildMarkerBasedEvents(text: string, markers: Marker[]): TimelineEvent[] {
  if (markers.length === 0) return [];

  const sorted = [...markers].sort((a, b) => a.index - b.index || a.endIndex - b.endIndex);

  // Remove duplicate markers generated by overlapping regexes.
  const unique: Marker[] = [];
  for (const marker of sorted) {
    const last = unique[unique.length - 1];
    if (!last) {
      unique.push(marker);
      continue;
    }
    const sameStart = marker.index === last.index;
    const containedByLast = marker.index >= last.index && marker.endIndex <= last.endIndex;
    if (sameStart || containedByLast) {
      continue;
    }
    unique.push(marker);
  }

  const events: TimelineEvent[] = [];

  for (let i = 0; i < unique.length; i++) {
    const current = unique[i];
    const next = unique[i + 1];
    const start = current.index;
    const end = next ? next.index : text.length;
    const content = text.slice(start, end).trim();
    if (content.length <= 3) continue;

    events.push({
      year: current.year,
      dateLabel: normalizeDateLabel(current.dateStr, current.year),
      content,
    });
  }

  return events.sort((a, b) => a.year - b.year);
}

// ── Chinese: split text at date markers and preserve full content ─────

function splitByChineseDates(text: string): TimelineEvent[] {
  // Find ALL date marker positions in the text
  const markers: Marker[] = [];

  // "1992年" / "1992 年起" / "1978 年至 1995 年"
  const yearRe = /(\d{4}\s*年(?:\s*(?:至|到|—|-|～|~)\s*\d{4}\s*年)?)/g;
  let m: RegExpExecArray | null;
  while ((m = yearRe.exec(text)) !== null) {
    const year = parseYearFromDateStr(m[0]);
    if (year !== null) {
      markers.push({ index: m.index, endIndex: m.index + m[0].length, dateStr: m[0].trim(), year });
    }
  }

  // "(-1983年）" / "（1978 年 - 1995 年）"
  const parenRe = /[（(]\s*(?:-|至|到|—|before|after|前|后)?\s*(\d{4})\s*年?\s*(?:[）)]|$)/g;
  while ((m = parenRe.exec(text)) !== null) {
    const year = parseInt(m[1], 10);
    // Also check if there's a label before the paren
    const labelBefore = text.substring(Math.max(0, m.index - 40), m.index).trim();
    const dateStr = labelBefore ? `${labelBefore}（${m[0].replace(/^[（(]\s*/, '').replace(/\s*[）)]$/, '')}）` : m[0];
    markers.push({ index: m.index, endIndex: m.index + m[0].length, dateStr, year });
  }

  // "20 世纪 90 年代"
  const centuryRe = /(\d{1,2}\s*世[纪紀]\s*\d{1,2}\s*年[代])/g;
  while ((m = centuryRe.exec(text)) !== null) {
    const year = parseYearFromDateStr(m[0]);
    if (year !== null) {
      markers.push({ index: m.index, endIndex: m.index + m[0].length, dateStr: m[0], year });
    }
  }

  return buildMarkerBasedEvents(text, markers);
}

// ── English: split text at date markers and preserve full content ──────

function splitByEnglishDates(text: string): TimelineEvent[] {
  const markers: Marker[] = [];

  // "in 1992" / "since 1983" / "by 2010" / "during 2005"
  const prepRe = /(in|around|about|circa|since|by|before|after|during|from)\s+(\d{4})\b/gi;
  let m: RegExpExecArray | null;
  while ((m = prepRe.exec(text)) !== null) {
    const year = parseInt(m[2], 10);
    markers.push({ index: m.index, endIndex: m.index + m[0].length, dateStr: m[0], year });
  }

  // Standalone year: "1992, the station opened..."
  // Only match if preceded by sentence boundary or start
  const soloRe = /(?:^|[.!?\n]\s*)(\d{4})\b/gm;
  while ((m = soloRe.exec(text)) !== null) {
    const year = parseInt(m[1], 10);
    // Avoid duplicates near preposition matches
    const nearPrep = markers.some(existing => Math.abs(existing.index - m!.index) < 5);
    if (!nearPrep) {
      markers.push({ index: m.index + m[0].indexOf(m[1]), endIndex: m.index + m[0].length, dateStr: m[1], year });
    }
  }

  // "between 1978 and 1995" / "from 1980 to 2000"
  const rangeRe = /(between|from)\s+(\d{4})\s+(and|to|until)\s+(\d{4})/gi;
  while ((m = rangeRe.exec(text)) !== null) {
    const startYear = parseInt(m[2], 10);
    markers.push({ index: m.index, endIndex: m.index + m[0].length, dateStr: m[0], year: startYear });
  }

  // "the 1980s" / "the 1990s"
  const decadeRe = /the\s+(\d{4})s/gi;
  while ((m = decadeRe.exec(text)) !== null) {
    const year = parseInt(m[1], 10);
    markers.push({ index: m.index, endIndex: m.index + m[0].length, dateStr: m[0], year });
  }

  return buildMarkerBasedEvents(text, markers);
}

// ── Main analysis ──────────────────────────────────────────────────────

function analyzeTimeline(text: string, language: 'en' | 'zh'): TimelineResult {
  const cleaned = text.trim();
  if (!cleaned || cleaned.length < 10) {
    return { events: [], hasTimeline: false, confidence: 0 };
  }

  const events = language === 'zh'
    ? splitByChineseDates(cleaned)
    : splitByEnglishDates(cleaned);

  const confidence = events.length >= 3 ? 90
    : events.length === 2 ? 70
    : events.length === 1 ? 40
    : 0;

  return {
    events,
    hasTimeline: events.length >= 1 && confidence >= 30,
    confidence,
  };
}

export { analyzeTimeline };
